# Velocity Configuration
# Updated for config version 2.0

[servers]
lobby = "minecraft:25566"

[forced-hosts]
"minecraft.fedecabre.com" = ["lobby"]

[advanced]
force-key-authentication = true

[query]
enabled = true
port = 25565
show-plugins = false